version: '3.8'

services:
  nginx:
    image: webproject-nginx
    container_name: nginx
    ports:
      - "80:80"   # host:container
    extra_hosts:
      - "pegawai-baru.test:127.0.0.1"
      - "www.pegawai-baru.test:127.0.0.1"
    volumes:
      - ../pegawai-baru:/var/www/pegawai-baru:ro  # Optional: mount folder html dari lokal
    networks:
      - app-net
      
  php56:
    image: webproject-php56
    container_name: php56
    ports:
      - "9056:9056"   # host:container
    volumes:
      - ../pegawai-baru:/var/www/pegawai-baru:ro  # Optional: mount folder html dari lokal
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
    

